# Generated by Django 4.2.17 on 2024-12-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='preceeding_question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(to='questions.answer'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='questionaires',
            field=models.ManyToManyField(to='questions.question'),
        ),
    ]
