# Generated by Django 4.2.17 on 2024-12-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_answer_preceeding_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='questionaires',
        ),
        migrations.AddField(
            model_name='answer',
            name='possible_questionnaires',
            field=models.ManyToManyField(to='questions.questionnaire'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='questions',
            field=models.ManyToManyField(related_name='Questionnaires', to='questions.question'),
        ),
    ]
