# Generated by Django 4.2.17 on 2024-12-17 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_possible_questionnaires_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='possible_questionnaires',
        ),
        migrations.RemoveField(
            model_name='question',
            name='possible_questionnaires',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='answers',
            field=models.ManyToManyField(to='questions.answer'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='first_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_of', to='questions.question'),
        ),
    ]
